colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
mainSections = [ "render", "unix", "about", "acgn" ]
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "plana-hero.png"
defaultFeaturedImage = "plana-profile.png"

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "plana-hero.png"

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = true
showComments = true
showZenMode = false
heroStyle = "thumbAndBackground"

[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false
heroStyle = "background"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false
heroStyle = "background"

[term]
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false
heroStyle = "background"

[firebase]

[fathomAnalytics]

[umamiAnalytics]
  websiteid = "e54a34b7-b153-41c0-a794-bb050c0c1abc"

[buymeacoffee]

[verification]
